export const MUTATION_KEY_LOGIN_AUTH = "LOGIN/AUTH";
export const MUTATION_KEY_LOGOUT_AUTH = "LOGOUT/AUTH";
export const MUTATION_KEY_LOGIN_VERIFY = "LOGIN/VERIFY";
export const MUTATION_KEY_CHANGE_QUEUE = "CHANGE-QUEUE";
export const MUTATION_KEY_CHANGE_SETTINGS = "CHANGE-SETTINGS";
