/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MainRouteImport } from './routes/_main'
import { Route as MainIndexRouteImport } from './routes/_main/index'
import { Route as MainSettingsIndexRouteImport } from './routes/_main/settings/index'
import { Route as MainSearchIndexRouteImport } from './routes/_main/search/index'
import { Route as MainFeedIndexRouteImport } from './routes/_main/feed/index'
import { Route as MainDownloadIndexRouteImport } from './routes/_main/download/index'
import { Route as MainUserIdRouteImport } from './routes/_main/user/$id'
import { Route as MainPlaylistIdRouteImport } from './routes/_main/playlist/$id'
import { Route as MainGenreIdRouteImport } from './routes/_main/genre/$id'
import { Route as MainCategoryTypeRouteImport } from './routes/_main/category/$type'
import { Route as MainArtistIdRouteImport } from './routes/_main/artist/$id'
import { Route as MainAlbumIdRouteImport } from './routes/_main/album/$id'
import { Route as MainSearchQueryIndexRouteImport } from './routes/_main/search/$query/index'
import { Route as MainSearchQueryCategoryRouteImport } from './routes/_main/search/$query/$category'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MainRoute = MainRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRoute,
} as any)
const MainSettingsIndexRoute = MainSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => MainRoute,
} as any)
const MainSearchIndexRoute = MainSearchIndexRouteImport.update({
  id: '/search/',
  path: '/search/',
  getParentRoute: () => MainRoute,
} as any)
const MainFeedIndexRoute = MainFeedIndexRouteImport.update({
  id: '/feed/',
  path: '/feed/',
  getParentRoute: () => MainRoute,
} as any)
const MainDownloadIndexRoute = MainDownloadIndexRouteImport.update({
  id: '/download/',
  path: '/download/',
  getParentRoute: () => MainRoute,
} as any)
const MainUserIdRoute = MainUserIdRouteImport.update({
  id: '/user/$id',
  path: '/user/$id',
  getParentRoute: () => MainRoute,
} as any)
const MainPlaylistIdRoute = MainPlaylistIdRouteImport.update({
  id: '/playlist/$id',
  path: '/playlist/$id',
  getParentRoute: () => MainRoute,
} as any)
const MainGenreIdRoute = MainGenreIdRouteImport.update({
  id: '/genre/$id',
  path: '/genre/$id',
  getParentRoute: () => MainRoute,
} as any)
const MainCategoryTypeRoute = MainCategoryTypeRouteImport.update({
  id: '/category/$type',
  path: '/category/$type',
  getParentRoute: () => MainRoute,
} as any)
const MainArtistIdRoute = MainArtistIdRouteImport.update({
  id: '/artist/$id',
  path: '/artist/$id',
  getParentRoute: () => MainRoute,
} as any)
const MainAlbumIdRoute = MainAlbumIdRouteImport.update({
  id: '/album/$id',
  path: '/album/$id',
  getParentRoute: () => MainRoute,
} as any)
const MainSearchQueryIndexRoute = MainSearchQueryIndexRouteImport.update({
  id: '/search/$query/',
  path: '/search/$query/',
  getParentRoute: () => MainRoute,
} as any)
const MainSearchQueryCategoryRoute = MainSearchQueryCategoryRouteImport.update({
  id: '/search/$query/$category',
  path: '/search/$query/$category',
  getParentRoute: () => MainRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof MainIndexRoute
  '/login': typeof LoginRoute
  '/album/$id': typeof MainAlbumIdRoute
  '/artist/$id': typeof MainArtistIdRoute
  '/category/$type': typeof MainCategoryTypeRoute
  '/genre/$id': typeof MainGenreIdRoute
  '/playlist/$id': typeof MainPlaylistIdRoute
  '/user/$id': typeof MainUserIdRoute
  '/download/': typeof MainDownloadIndexRoute
  '/feed/': typeof MainFeedIndexRoute
  '/search/': typeof MainSearchIndexRoute
  '/settings/': typeof MainSettingsIndexRoute
  '/search/$query/$category': typeof MainSearchQueryCategoryRoute
  '/search/$query/': typeof MainSearchQueryIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof MainIndexRoute
  '/album/$id': typeof MainAlbumIdRoute
  '/artist/$id': typeof MainArtistIdRoute
  '/category/$type': typeof MainCategoryTypeRoute
  '/genre/$id': typeof MainGenreIdRoute
  '/playlist/$id': typeof MainPlaylistIdRoute
  '/user/$id': typeof MainUserIdRoute
  '/download': typeof MainDownloadIndexRoute
  '/feed': typeof MainFeedIndexRoute
  '/search': typeof MainSearchIndexRoute
  '/settings': typeof MainSettingsIndexRoute
  '/search/$query/$category': typeof MainSearchQueryCategoryRoute
  '/search/$query': typeof MainSearchQueryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_main': typeof MainRouteWithChildren
  '/login': typeof LoginRoute
  '/_main/': typeof MainIndexRoute
  '/_main/album/$id': typeof MainAlbumIdRoute
  '/_main/artist/$id': typeof MainArtistIdRoute
  '/_main/category/$type': typeof MainCategoryTypeRoute
  '/_main/genre/$id': typeof MainGenreIdRoute
  '/_main/playlist/$id': typeof MainPlaylistIdRoute
  '/_main/user/$id': typeof MainUserIdRoute
  '/_main/download/': typeof MainDownloadIndexRoute
  '/_main/feed/': typeof MainFeedIndexRoute
  '/_main/search/': typeof MainSearchIndexRoute
  '/_main/settings/': typeof MainSettingsIndexRoute
  '/_main/search/$query/$category': typeof MainSearchQueryCategoryRoute
  '/_main/search/$query/': typeof MainSearchQueryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/album/$id'
    | '/artist/$id'
    | '/category/$type'
    | '/genre/$id'
    | '/playlist/$id'
    | '/user/$id'
    | '/download/'
    | '/feed/'
    | '/search/'
    | '/settings/'
    | '/search/$query/$category'
    | '/search/$query/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/album/$id'
    | '/artist/$id'
    | '/category/$type'
    | '/genre/$id'
    | '/playlist/$id'
    | '/user/$id'
    | '/download'
    | '/feed'
    | '/search'
    | '/settings'
    | '/search/$query/$category'
    | '/search/$query'
  id:
    | '__root__'
    | '/_main'
    | '/login'
    | '/_main/'
    | '/_main/album/$id'
    | '/_main/artist/$id'
    | '/_main/category/$type'
    | '/_main/genre/$id'
    | '/_main/playlist/$id'
    | '/_main/user/$id'
    | '/_main/download/'
    | '/_main/feed/'
    | '/_main/search/'
    | '/_main/settings/'
    | '/_main/search/$query/$category'
    | '/_main/search/$query/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MainRoute: typeof MainRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/settings/': {
      id: '/_main/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof MainSettingsIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/search/': {
      id: '/_main/search/'
      path: '/search'
      fullPath: '/search/'
      preLoaderRoute: typeof MainSearchIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/feed/': {
      id: '/_main/feed/'
      path: '/feed'
      fullPath: '/feed/'
      preLoaderRoute: typeof MainFeedIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/download/': {
      id: '/_main/download/'
      path: '/download'
      fullPath: '/download/'
      preLoaderRoute: typeof MainDownloadIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/user/$id': {
      id: '/_main/user/$id'
      path: '/user/$id'
      fullPath: '/user/$id'
      preLoaderRoute: typeof MainUserIdRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/playlist/$id': {
      id: '/_main/playlist/$id'
      path: '/playlist/$id'
      fullPath: '/playlist/$id'
      preLoaderRoute: typeof MainPlaylistIdRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/genre/$id': {
      id: '/_main/genre/$id'
      path: '/genre/$id'
      fullPath: '/genre/$id'
      preLoaderRoute: typeof MainGenreIdRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/category/$type': {
      id: '/_main/category/$type'
      path: '/category/$type'
      fullPath: '/category/$type'
      preLoaderRoute: typeof MainCategoryTypeRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/artist/$id': {
      id: '/_main/artist/$id'
      path: '/artist/$id'
      fullPath: '/artist/$id'
      preLoaderRoute: typeof MainArtistIdRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/album/$id': {
      id: '/_main/album/$id'
      path: '/album/$id'
      fullPath: '/album/$id'
      preLoaderRoute: typeof MainAlbumIdRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/search/$query/': {
      id: '/_main/search/$query/'
      path: '/search/$query'
      fullPath: '/search/$query/'
      preLoaderRoute: typeof MainSearchQueryIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/search/$query/$category': {
      id: '/_main/search/$query/$category'
      path: '/search/$query/$category'
      fullPath: '/search/$query/$category'
      preLoaderRoute: typeof MainSearchQueryCategoryRouteImport
      parentRoute: typeof MainRoute
    }
  }
}

interface MainRouteChildren {
  MainIndexRoute: typeof MainIndexRoute
  MainAlbumIdRoute: typeof MainAlbumIdRoute
  MainArtistIdRoute: typeof MainArtistIdRoute
  MainCategoryTypeRoute: typeof MainCategoryTypeRoute
  MainGenreIdRoute: typeof MainGenreIdRoute
  MainPlaylistIdRoute: typeof MainPlaylistIdRoute
  MainUserIdRoute: typeof MainUserIdRoute
  MainDownloadIndexRoute: typeof MainDownloadIndexRoute
  MainFeedIndexRoute: typeof MainFeedIndexRoute
  MainSearchIndexRoute: typeof MainSearchIndexRoute
  MainSettingsIndexRoute: typeof MainSettingsIndexRoute
  MainSearchQueryCategoryRoute: typeof MainSearchQueryCategoryRoute
  MainSearchQueryIndexRoute: typeof MainSearchQueryIndexRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainIndexRoute: MainIndexRoute,
  MainAlbumIdRoute: MainAlbumIdRoute,
  MainArtistIdRoute: MainArtistIdRoute,
  MainCategoryTypeRoute: MainCategoryTypeRoute,
  MainGenreIdRoute: MainGenreIdRoute,
  MainPlaylistIdRoute: MainPlaylistIdRoute,
  MainUserIdRoute: MainUserIdRoute,
  MainDownloadIndexRoute: MainDownloadIndexRoute,
  MainFeedIndexRoute: MainFeedIndexRoute,
  MainSearchIndexRoute: MainSearchIndexRoute,
  MainSettingsIndexRoute: MainSettingsIndexRoute,
  MainSearchQueryCategoryRoute: MainSearchQueryCategoryRoute,
  MainSearchQueryIndexRoute: MainSearchQueryIndexRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  MainRoute: MainRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
